- name: Install discord
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
    method: user

- name: Install spotify
  community.general.flatpak:
    name: com.spotify.Client
    state: present
    method: user

- name: Install KeePassXC
  community.general.flatpak:
    name: org.keepassxc.KeePassXC
    state: present
    method: user
    


